config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get 'up' => 'rails/health#show', as: :rails_health_check

  resources :wines

  # root to: 'application#go_home'
  root to: 'wines#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wine.rb
# frozen_string_literal: true

# class that manage Wines objects
class Wine < ApplicationRecord
  include MeiliSearch::Rails
  extend Pagy::Meilisearch
  ActiveRecord_Relation.include Pagy::Meilisearch

  SEARCH_SYNONYMS = {
    red: %w[tinto],
    tinto: %w[red],
    white: %w[branco],
    branco: %w[white],
    sparkling: %w[espumante],
    espumante: %w[sparkling]
  }.freeze

  RED       = 'reds'
  ROSE      = 'rose'
  WHITE     = 'whites'
  SPARKLING = 'sparkling'

  meilisearch do
    attribute %i[winery name wine_type location]
    attribute :average_rating do
      average_rating.to_f
    end

    searchable_attributes %i[winery name wine_type location]

    filterable_attributes %i[wine_type]

    sortable_attributes %i[created_at updated_at average_rating]

    synonyms SEARCH_SYNONYMS
  end

  validates :winery, :name, :wine_type, :location, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
  # def go_home
  #   if user_signed_in?
  #     if current_user && current_user.superuser?
  #       redirect_to tenants_path
  #     else
  #       redirect_to orders_path
  #     end
  #   else
  #     redirect_to new_user_session_path
  #   end
  # end
end

app/controllers/wines_controller.rb
# frozen_string_literal: true

# class that manage wines records
class WinesController < ApplicationController
  def index
    wines = Wine.pagy_search(params[:query])
    @pagy, @wines = pagy_meilisearch(wines, items: 10)
  end
end

# Wine.search('italy', filter: ['wine_type=red'], sort: ['created_at:desc'])

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def render_flash_stream
    turbo_stream.update 'flash', partial: 'layouts/flash'
  end

  def content_id
    "#{controller_name.underscore}_#{action_name}"
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_flash.html.erb
<div class="flashes">
  <% flash.each do |type, message| %>
    <%= content_tag(:div, message, class: "flash #{type}",
          data: { controller: "flash" }) %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <p>
    A venda de bebidas alcoólicas é proibida para menores de 18 anos. Aprecie com moderação. Se beber, não dirija.
  </p>
  <p>
    © 2024. Wine-Shop Comércio de Vinhos S.A. - CNPJ: 88.250.655/0001-69. Av. Principal, 1000 - Centro, São Paulo - SP.
  </p>
</footer>

app/views/layouts/_header.html.erb
<div class='header w-full flex-row justify-content-between'>
  <div class='title', id='home_link'>
    <%= link_to "WINE SHOP 2.0", wines_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wineshop2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div id="flash">
      <%= render "layouts/flash" %>
    </div>

    <main>
      <div id="<%= content_id %>">
        <%= yield %>
      </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/wines/_wine.html.erb
<%= tag.div id: dom_id(wine), class:'card flex-column' do %>
  <div class='wine-rating align-item-start'>
    <i class="bi bi-star"></i>
    <p><%= wine.average_rating%></p>
  </div>
  <div class='photo flex-column align-item-center'>
    <img src=<%= wine.image_url%> alt="">
  </div>
  <div class='card-info'>
    <p class='wine-name'><%= wine.name %></p>
    <p class='wine-info'><%= wine.location %></p>
  </div>
<% end %>

app/views/wines/index.html.erb
<div class='w-full flex-column', data-controller="search">
  <div class='main flex-row'>
    <div class='flex-column'>
      <div class='search flex-row w-full justify-content-end' data-controller="search">
        <%= form_with(url: wines_path, method: :get,
              data: {
                turbo_frame: 'results',
                turbo_action: 'advance',
                controller: 'search',
                action: 'input->search#submit'
              }) do |form| %>
            <%= form.search_field :query, placeholder: ' Search', value: params[:query] %>
        <% end %>
      </div>

      <%= turbo_frame_tag "results" do %>
        <div class='w-full container flex-row flex-wrap'>
          <%= render @wines %>
        </div>

        <div class='w-full flex-row justify-content-around', data-turbo_frame='results', data-turbo_action='advance' >
          <%== pagy_bootstrap_nav(@pagy) %>
        </div>
      <% end %>
    </div>
  </div>
</div>